### PR TITLE
Skip test if radar has not recently been updated

### LINKED ISSUE #112: Sometimes test fail for a specific radar not being available
The discussion here is an example for Sweden  (https://github.com/aloftdata/getRad/actions/runs/17037693287/job/48468086663):

> Hmm it seem part of the swedish radar network does not produce data:
> This works: https://opendata-download-radar.smhi.se/api/version/latest/area/balsta/product/qcvol
> While this radar has a 404: https://opendata-download-radar.smhi.se/api/version/latest/area/atvidaberg/product/qcvol
> Maybe I will check if it is transient and retry later today? 

 _Originally posted by @bart1 in [#60](https://github.com/aloftdata/getRad/issues/60#issuecomment-3204787609)_

As it is the first time this happens lets keep an eye out if the problem is more frequent an in that case make the test fail gracefully without automatically skipping for permanent failures

### PR DESCRIPTION
**Pull request by bart1**
Fixes #112 for `se`

### CODE REVIEW

**Comment by bart1** [comment]
Test now indeed are skipped if there is no recent data: https://github.com/aloftdata/getRad/actions/runs/17094297523/job/48475000215?pr=113#step:6:204

**Comment by PietrH** [comment]
Is there any way we could wrap this into a custom skip function? skip_if_radar_not_updated() ? Or if not, skip_if_se_not_updated() ?

File: tests/testthat/test-get_pvol_se.R [hunk 1]
```diff
@@ -1,6 +1,12 @@
 test_that("Pvol for Sweden can be downloaded", {
   skip_if_offline("opendata-download-radar.smhi.se")
   time <- as.POSIXct(Sys.time(), tz = "Europe/Helsinki") - lubridate::hours(10)
+  skip_if_not(
+    httr2::request("https://opendata-download-radar.smhi.se/api/version/latest/area/") |>
+      httr2::req_perform() |> httr2::resp_body_json() |> purrr::chuck("areas") |>
+      purrr::map(~ as.data.frame(.x)) |> dplyr::bind_rows() |> dplyr::filter(key == "atvidaberg") |>
+      purrr::chuck("updated") |> lubridate::as_datetime() > time
```
Comment (PietrH) [inline tests/testthat/test-get_pvol_se.R:8]:
```suggestion
      purrr::chuck("updated") |> lubridate::as_datetime() > time,
      message = "atvidaberg was not updated in the last 10 hours"
```

File: tests/testthat/test-get_pvol_se.R [hunk 2]
```diff
@@ -12,6 +18,13 @@ test_that("Pvol for Sweden can be downloaded", {
 test_that("Pvol for Sweden fails out of time range", {
   skip_if_offline("opendata-download-radar.smhi.se")
   time <- Sys.time() - lubridate::hours(40)
+  skip_if_not(
+    httr2::request("https://opendata-download-radar.smhi.se/api/version/latest/area/") |>
+      httr2::req_perform() |> httr2::resp_body_json() |> purrr::chuck("areas") |>
+      purrr::map(~ as.data.frame(.x)) |> dplyr::bind_rows() |> dplyr::filter(key == "hudiksvall") |>
+      purrr::chuck("updated") |> lubridate::as_datetime() > time
```
Comment (PietrH) [inline tests/testthat/test-get_pvol_se.R:25]:
```suggestion
      purrr::chuck("updated") |> lubridate::as_datetime() > time,
      message = "hudiksvall was not updated in the last 40 hours"
```

File: tests/testthat/test-get_pvol_se.R [hunk 3]
```diff
@@ -1,6 +1,12 @@
 test_that("Pvol for Sweden can be downloaded", {
   skip_if_offline("opendata-download-radar.smhi.se")
   time <- as.POSIXct(Sys.time(), tz = "Europe/Helsinki") - lubridate::hours(10)
+  skip_if_not(
```
Comment (PietrH) [inline tests/testthat/test-get_pvol_se.R:4]: A helper for skipping might be useful, do you think this could be generalised to other tests?

**Review by PietrH — CHANGES_REQUESTED** [review]
