### PR TITLE
fix #135 read local vpts files

### LINKED ISSUE #135: Using local files as source in get_vpts?
I would like to iteratively load data from Aloft using getRad::get_vpts, for specific radar and time intervals, do some filtering / cleaning and save a local version (in "csv.gz") of the clean data frame. Because I need to go through several radars / years it takes a lot of time to iteratively load the data I want to work with from Aloft (and sometimes fail - see #134). Could it be possible to add the option of using a local directory containing the data previously downloaded (e.g., from Zenodo) as source in the get_vpts function?

This would drastically reduce the processing time and allow to specify radars / time intervals.

### PR DESCRIPTION
**Pull request by bart1**
The  implementation for local data reading is quite flexible to for example make it possible to also read daily data. It is mostly controlled through a glue formatting string as documented (please check if you understand).

Currently if no file is found the function fails. If some data is found it warns about the data not found. However it could be whole radars are absent and thus not read with only a warning

### CODE REVIEW

File: R/get_vpts.R [hunk 1]
```diff
@@ -190,7 +209,9 @@ get_vpts <- function(
     switch(
       dplyr::case_when(
         source == "rmi" ~ "rmi",
-        source %in% eval(formals("get_vpts_aloft")$source) ~ "aloft"
+        source %in% eval(formals("get_vpts_aloft")$source) ~ "aloft",
```
Comment (PietrH) [inline R/get_vpts.R:212]: What if the local directory is called `rmi` or `aloft`?

File: R/get_vpts_local.R [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+        radar = .x,
+        year = lubridate::year(dates),
+        month = sprintf("%02i", lubridate::month(dates)),
+        day = sprintf("%02i", lubridate::day(dates)),
+        date = dates
+      ))
+    ) |>
+    purrr::set_names(radar)
+  full_paths <- purrr::map(file_paths, ~ file.path(directory, .x))
+  s <- purrr::map(full_paths, file.exists)
```
Comment (PietrH) [inline R/get_vpts_local.R]: Does it make sense to output to a logical vector here instead of a list? Since you unlist later? 

Do you even need map? Can you not just go `file.exists(full_paths)` ? Otherwise: `purrr::map_lgl(full_paths, file.exists)`.

I'd personally call this something like files_exist instead of s.

File: tests/testthat/test-get_vpts_local.R [hunk 3]
```diff
@@ -0,0 +1,109 @@
+dir <- tempdir()
```
Comment (PietrH) [inline tests/testthat/test-get_vpts_local.R]: FYI: I like withr over tempdir() and unlink(), it's neater in case unlink doesn't get evaluated because of a crash or error. This works just fine though!

**Review by PietrH — CHANGES_REQUESTED** [review]
Well done, small suggestions. 👍

File: R/get_vpts.R (hunk 1 above)
Comment (bart1) [reply R/get_vpts.R:212]: Then you provide the full file path ;) or `"../aloft"`, to me that is acceptable

Comment (PietrH) [reply R/get_vpts.R:212]: Sure!

File: R/get_vpts_local.R (hunk 2 above)
Comment (bart1) [reply R/get_vpts_local.R]: I improved the naming, it does however needs to be a `map` function since I keep the radars separated in a list. I think this is what `get_vpts` expects

File: tests/testthat/test-get_vpts_local.R (hunk 3 above)
Comment (bart1) [reply tests/testthat/test-get_vpts_local.R]: done

**Comment by PietrH** [comment]
Thanks for making the changes, good to merge if CI passes.

**Review by PietrH — APPROVED** [review]
