### PR TITLE
Remove fix of missing how data (fix #102)

### LINKED ISSUE #102: `CZ` fails for alreading existing group
I guess they added the how group to the data
``` r
require(getRad)
#> Loading required package: getRad
get_pvol("czska", Sys.time()-700)
#> Error in `dplyr::mutate()`:
#> ℹ In argument: `mut = purrr::map(...)`.
#> Caused by error in `purrr::map()`:
#> ℹ In index: 1.
#> Caused by error in `rhdf5::H5Gcreate()`:
#> ! HDF5. Symbol table. Unable to initialize object.
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.5.1 (2025-06-13)
#>  os       Ubuntu 22.04.5 LTS
#>  system   x86_64, linux-gnu
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       Europe/Amsterdam
#>  date     2025-08-11
#>  pandoc   3.4 @ /usr/lib/rstudio/resources/app/bin/quarto/bin/tools/x86_64/ (via rmarkdown)
#>  quarto   1.6.42 @ /usr/lib/rstudio/resources/app/bin/quarto/bin/quarto
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package      * version date (UTC) lib source
#>  cachem         1.1.0   2024-05-16 [1] CRAN (R 4.5.1)
#>  cli            3.6.5   2025-04-23 [1] CRAN (R 4.5.1)
#>  curl           6.4.0   2025-06-22 [1] CRAN (R 4.5.1)
#>  digest         0.6.37  2024-08-19 [1] CRAN (R 4.5.1)
#>  dplyr          1.1.4   2023-11-17 [1] CRAN (R 4.5.1)
#>  evaluate       1.0.4   2025-06-18 [1] CRAN (R 4.5.1)
#>  fastmap        1.2.0   2024-05-15 [1] CRAN (R 4.5.1)
#>  fs             1.6.6   2025-04-12 [1] CRAN (R 4.5.1)
#>  generics       0.1.4   2025-05-09 [1] CRAN (R 4.5.1)
#>  getRad       * 0.2.0   2025-07-11 [1] local
#>  glue           1.8.0   2024-09-30 [1] CRAN (R 4.5.1)
#>  htmltools      0.5.8.1 2024-04-04 [1] CRAN (R 4.5.1)
#>  httr2          1.1.2   2025-03-26 [1] CRAN (R 4.5.1)
#>  knitr          1.50    2025-03-16 [1] CRAN (R 4.5.1)
#>  lifecycle      1.0.4   2023-11-07 [1] CRAN (R 4.5.1)
#>  lubridate      1.9.4   2024-12-08 [1] CRAN (R 4.5.1)
#>  magrittr       2.0.3   2022-03-30 [1] CRAN (R 4.5.1)
#>  pillar         1.11.0  2025-07-04 [1] CRAN (R 4.5.1)
#>  pkgconfig      2.0.3   2019-09-22 [1] CRAN (R 4.5.1)
#>  purrr          1.1.0   2025-07-10 [1] CRAN (R 4.5.1)
#>  R6             2.6.1   2025-02-15 [1] CRAN (R 4.5.1)
#>  rappdirs       0.3.3   2021-01-31 [1] CRAN (R 4.5.1)
#>  reprex         2.1.1   2024-07-06 [1] CRAN (R 4.5.1)
#>  rhdf5          2.52.1  2025-06-08 [1] Bioconductor 3.21 (R 4.5.1)
#>  rhdf5filters   1.20.0  2025-04-15 [1] Bioconductor 3.21 (R 4.5.1)
#>  Rhdf5lib       1.30.0  2025-04-15 [1] Bioconductor 3.21 (R 4.5.1)
#>  rlang          1.1.6   2025-04-11 [1] CRAN (R 4.5.1)
#>  rmarkdown      2.29    2024-11-04 [1] CRAN (R 4.5.1)
#>  rstudioapi     0.17.1  2024-10-22 [1] CRAN (R 4.5.1)
#>  sessioninfo    1.2.3   2025-02-05 [1] CRAN (R 4.5.1)
#>  tibble         3.3.0   2025-06-08 [1] CRAN (R 4.5.1)
#>  tidyr          1.3.1   2024-01-24 [1] CRAN (R 4.5.1)
#>  tidyselect     1.2.1   2024-03-11 [1] CRAN (R 4.5.1)
#>  timechange     0.3.0   2024-01-18 [1] CRAN (R 4.5.1)
#>  vctrs          0.6.5   2023-12-01 [1] CRAN (R 4.5.1)
#>  withr          3.0.2   2024-10-28 [1] CRAN (R 4.5.1)
#>  xfun           0.52    2025-04-02 [1] CRAN (R 4.5.1)
#>  xml2           1.3.8   2025-03-14 [1] CRAN (R 4.5.1)
#>  yaml           2.3.10  2024-07-26 [1] CRAN (R 4.5.1)
#> 
#>  [1] /home/bart/R/x86_64-pc-linux-gnu-library/4.5
#>  [2] /usr/local/lib/R/site-library
#>  [3] /usr/lib/R/site-library
#>  [4] /usr/lib/R/library
#>  * ── Packages attached to the search path.
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

<sup>Created on 2025-08-11 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by bart1**

### CODE REVIEW

**Comment by bart1** [comment]
Prima ik denk dat dit ook de checks voor andere moet fixen dan dan moet die terug gemerged worden in #97

**Comment by bart1** [comment]
As there is no historic data available the is no need to implement a conditional check if it needs to be added

File: tests/testthat/test-get_pvol.R [hunk 1]
```diff
@@ -123,3 +123,22 @@ test_that("multiple timestamps and radars work", {
...
+})
+
+test_that("Mixed radar vector + 9 minute interval", {
+  skip_if_offline()
+  time_utc <- lubridate::floor_date(Sys.time() - lubridate::hours(12), "5 mins")
+  dt_int <- lubridate::interval(time_utc, time_utc + lubridate::minutes(9))
+  suppressMessages(pvols <- getRad::get_pvol(c("KABR", "czska"), dt_int))
+  expect_true(is.list(pvols))
+  expect_gt(length(pvols), 2)
+  expect_true(all(purrr::map_lgl(pvols, ~ inherits(.x, "pvol"))))
```
Comment (PietrH) [inline tests/testthat/test-get_pvol.R:143]:
```suggestion
    purrr::walk(pvols, ~expect_s3_class(.x, "pvol"))
```

I prefer using testthat helpers, using purr in this way will fail sooner than using `all()`

File: tests/testthat/test-get_pvol.R [hunk 2]
```diff
@@ -123,3 +123,22 @@ test_that("multiple timestamps and radars work", {
...
+  expect_true(is.list(pvols))
+  expect_gt(length(pvols), 0)
+  expect_true(all(purrr::map_lgl(pvols, ~ inherits(.x, "pvol"))))
+})
+
+test_that("Mixed radar vector + 9 minute interval", {
+  skip_if_offline()
+  time_utc <- lubridate::floor_date(Sys.time() - lubridate::hours(12), "5 mins")
+  dt_int <- lubridate::interval(time_utc, time_utc + lubridate::minutes(9))
+  suppressMessages(pvols <- getRad::get_pvol(c("KABR", "czska"), dt_int))
```
Comment (PietrH) [inline tests/testthat/test-get_pvol.R:140]: This actually fetches quite a bit of data, any way we could make this smaller to save no bandwidth and make the tests run quicker? A shorter interval maybe?

File: tests/testthat/test-get_pvol.R [hunk 3]
```diff
@@ -123,3 +123,22 @@ test_that("multiple timestamps and radars work", {
...
+test_that("Mixed radar vector (single timestamp)", {
+  skip_if_offline()
+  time_utc <- lubridate::floor_date(Sys.time() - lubridate::hours(12), "5 mins")
+  suppressMessages(pvols <- getRad::get_pvol(c("KABR", "czska"), time_utc))
+  expect_true(is.list(pvols))
+  expect_gt(length(pvols), 0)
+  expect_true(all(purrr::map_lgl(pvols, ~ inherits(.x, "pvol"))))
+})
+
+test_that("Mixed radar vector + 9 minute interval", {
```
Comment (PietrH) [inline tests/testthat/test-get_pvol.R:136]: Any reason why we need to test a 9 minute interval specifically?

File: tests/testthat/test-get_pvol_us.R [hunk 4]
```diff
@@ -32,33 +32,25 @@ test_that("NEXRAD polar volume correct time is downloaded", {
...
 
-test_that("Mixed radar vector + 9 minute interval", {
-  skip_if_offline()
-  suppressMessages(pvols <- getRad::get_pvol(c("KABR", "czska"), dt_int))
-  expect_true(is.list(pvols))
-  expect_gt(length(pvols), 2)
-  expect_true(all(purrr::map_lgl(pvols, ~ inherits(.x, "pvol"))))
-})
+
 test_that("Caching of keys works", {
```
Comment (PietrH) [inline tests/testthat/test-get_pvol_us.R:41]: nitpick: I'm not the biggest fan of the `system.time()` based testing, there might be slowdowns on the test runner. I see why you skip this test on CRAN. 

Is checking for the presence for the key in the cache not enough? 

We could also use withr to set a local option to overwrite the default cache, and that way we'll be super certain both of cache location and that it starts as empty.

File: tests/testthat/test-get_pvol_us.R [hunk 5]
```diff
@@ -32,33 +32,25 @@ test_that("NEXRAD polar volume correct time is downloaded", {
...
+    "list_nexrad_keys_kggw_2025-02-04_historic", "list_nexrad_keys_kggw_2025-02-03_historic",
+    "list_nexrad_keys_kggw_2025-02-02_historic"
+  ) %in% getOption("getRad.cache")$keys()))
+  time_used<-system.time(.most_representative_nexrad_key(t, r))["elapsed"]
   expect_true(all(c(
     "list_nexrad_keys_kggw_2025-02-04_historic", "list_nexrad_keys_kggw_2025-02-03_historic",
     "list_nexrad_keys_kggw_2025-02-02_historic"
   ) %in% getOption("getRad.cache")$keys()))
-  expect_lt(system.time(.most_representative_nexrad_key(t, r))["elapsed"], .025)
+  expect_lt(system.time(.most_representative_nexrad_key(t, r))["elapsed"], time_used * 0.25)
```
Comment (PietrH) [inline tests/testthat/test-get_pvol_us.R]: 0.25 is a magic number, maybe just specify you want it to be 4x faster at least?

File: tests/testthat/test-get_pvol.R (hunk 2 above)
Comment (bart1) [reply tests/testthat/test-get_pvol.R:140]: I think it is good to test that cross country reading of pvols works therefore I designed the test like this

File: tests/testthat/test-get_pvol_us.R (hunk 5 above)
Comment (bart1) [reply tests/testthat/test-get_pvol_us.R]: It is doing the later I use this setup to check that the cache is also used therefore I prefer something like this. Otherwise you could have filled a cache your not using

File: tests/testthat/test-get_pvol_us.R (hunk 4 above)
Comment (bart1) [reply tests/testthat/test-get_pvol_us.R:41]: I think test that is anyway run in a separate environment. I already check the files are not present now (see `expect_false`). I do the time based check to ensure the cache is actually used. I think this design should be pretty robust looking for a relative speed increase

**Comment by bart1** [comment]
@PietrH once merges I will move this into the Sweden branch and also merge that one. I commited your suggestions.

**Review by PietrH — APPROVED** [review]
